#!/usr/bin/env python3
import os

package_to_install = ["picom", "git", "neovim", "tmux", "curl", "python3-pip", "nodejs"]

def configure_nvim():
    os.system("sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'")
    os.system("nvim +PlugInstall +qall")
    os.system("nvim \"+CocInstall coc-clangd coc-cmake\" +qall")
    os.system("pip3 install pynvim --upgrade")

if __name__ == "__main__":
    os.system("sudo xbps-install " + ' '.join(package_to_install))
    os.system("git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm")

