#!/usr/bin/env python3
import os

if __name__ == "__main__":
    os.system("apt-get install neovim -y")
    os.system("sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'")
    os.system("nvim +PlugInstall +qall")
    os.system("apt-get install clangd-10")
    os.system("update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-10 100")



 

