theme = "mytheme"

[editor]
scroll-lines=1
mouse=false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "bar"

[keys.normal]
"A-c" = "copy_selection_on_prev_line"

[keys.normal."space"]
"f" = "file_picker_in_current_directory"
"F" = "file_picker"
